/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_mrxiexie_jni_JNI */

#ifndef _Included_cn_mrxiexie_jni_JNI
#define _Included_cn_mrxiexie_jni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_mrxiexie_jni_JNI
 * Method:    sqrt
 * Signature: ([I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_cn_mrxiexie_jni_JNI_sqrt
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     cn_mrxiexie_jni_JNI
 * Method:    max
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_mrxiexie_jni_JNI_max
  (JNIEnv *, jclass);

/*
 * Class:     cn_mrxiexie_jni_JNI
 * Method:    min
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_mrxiexie_jni_JNI_min
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
