/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_mrxiexie_jni_JNI */

#ifndef _Included_cn_mrxiexie_jni_JNI
#define _Included_cn_mrxiexie_jni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_mrxiexie_jni_JNI
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_mrxiexie_jni_JNI_hello
  (JNIEnv *, jclass);

/*
 * Class:     cn_mrxiexie_jni_JNI
 * Method:    getPhone
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_mrxiexie_jni_JNI_getPhone
  (JNIEnv *, jclass);

/*
 * Class:     cn_mrxiexie_jni_JNI
 * Method:    isHello
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_mrxiexie_jni_JNI_isHello
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_mrxiexie_jni_JNI
 * Method:    exec
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_mrxiexie_jni_JNI_exec
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
